version: '3.4'

services:

  translator:
    image: tranzl8r-translator
    build:
      context: .
      dockerfile: Tranzl8R.TranslationService/Dockerfile
    env_file:
      - .env
    deploy:
      replicas: 10

  ui:
    image: tranzl8r-ui
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: Tranzl8R.Web/Dockerfile
    env_file:
      - .env

  orleans-dashboard:
    image: tranzl8r-dashboard
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: Tranzl8R.OrleansDashboard/Dockerfile
    env_file:
      - .env